### ISSUE TITLE
HTTPS in request file

### ISSUE THREAD

**Issue by B4RD4k** [Charlie-belmer/nosqli#5]
Hi,
When using the Burp request file there is no option to set force-SSL or something like that, so the connection will be initiated through HTTPS nor HTTP.

Any recommendation?

Thanks

**Comment by Charlie-belmer** [comment]
Hey @B4RD4k, right now it just takes a plain request file, not a burp one. That said, proper reading and running against burp request files is on my roadmap, and I'll likely implement it before I get to data exfil, since it's a lot easier to do.

**Comment by B4RD4k** [comment]
thanks =] 

In the above-mentioned HTTP request, does it over HTTPS?
This is the missing part i have.

**Comment by Charlie-belmer** [comment]
Thanks, You're absolutely right! It was defaulting to HTTP. I have just added an https option that can be passed, which will initiate the request file to https. Just published, please give it a spin and let me know how it works. I'll close this issue for now, but please re-open if you have any problems.

**Comment by B4RD4k** [comment]
Thanks 👍
