### ISSUE TITLE
Too Many Open Files Error

### ISSUE THREAD

**Issue by Himself132** [Charlie-belmer/nosqli#9]
Hello - love your tool, only one that works well scanning for nosqli.  

I am testing a POST request that eventually hits a mongoDB and checking for nosqli using your tool. The POST request is something like this and it seems to run for a long time and eventually comes up with an error from the Linux OS saying "2021/07/23 17:25:33 open nosqli_test_request.txt: too many open files".  Is there something i am doing wrong or are there limitations to the number of nested arrays or number of parameters or something?

`{
	"tagId": "TAG_GUID",
	"userId": "USER_GUID",
	"metadata": {
		"cellSelection": {
			"columnId": "column_name",
			"taskId": "TASK_GUID",
			"rowIndex": 6
		}
	}
}`

**Comment by harshkolhatkar** [comment]
I'm getting the same error and was wondering why that could be happening. I tried setting higher file limits for all users by extending hard and soft limits to 65536 in /etc/security/limits.conf but I still get the same error.

Also, one scan of the similar payload POST requests takes like an hour to complete, is that expected?

**Comment by Charlie-belmer** [comment]
Hopefully @beckler's latest contribution fixes this. If you see it again, please re-open!
